import paramiko, os
BASE = os.path.dirname(os.path.abspath(__file__))
_SERVER_IP = os.getenv('SERVER_IP', '')
_SERVER_PASS = os.getenv('SERVER_PASSWORD', '')
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect(_SERVER_IP, username='root', password=_SERVER_PASS, timeout=15, allow_agent=False, look_for_keys=False)
sftp = ssh.open_sftp()
sftp.put(os.path.join(BASE, 'outputs', 'card-game.html'), '/var/www/game/public/index.html')
sftp.close()
stdin, stdout, stderr = ssh.exec_command('nginx -s reload')
print('reload:', stdout.read().decode(), stderr.read().decode())
ssh.close()
print('Done!')
